name: A job to create and delete review apps
on:
  pull_request:
    types: [opened, reopened, closed, synchronize]
jobs:
  automate-review-app:
    runs-on: ubuntu-latest
    name: A job to create and delete review apps
    steps:
      - uses: actions/checkout@v3
      - uses: pmbanugo/heroku-review-app-actions@v2.0.0
        with:
          api-key: ${{ secrets.HEROKU_API_KEY }}
          pipeline-id: ${{ secrets.HEROKU_PIPELINE_ID }}
          base-name: getting-started
          file-glob: "* .prettierrc"
      - name: Comment on commit
        uses: phulsechinmay/rewritable-pr-comment@v0.2.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMENT_IDENTIFIER: "Deploy"
          message: |
            I deployed a review app for you to try out this pull request 👇🏽
            Heroku App: ${{ steps.deploy.outputs.url }}
